module.exports = {
  projects: [
    '<rootDir>/apps/picking',
    '<rootDir>/apps/shell',
    '<rootDir>/apps/legacy',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/picking/features/trip-summary',
    '<rootDir>/libs/picking/data/api',
    '<rootDir>/libs/picking/types',
    '<rootDir>/libs/picking/data/mocks',
    '<rootDir>/apps/picking-api',
    '<rootDir>/libs/shared/global-state',
    '<rootDir>/libs/shared/utility',
    '<rootDir>/libs/shared/feature-flags',
    '<rootDir>/libs/picking/data/api-contracts',
    '<rootDir>/libs/picking/features/trip-item',
    '<rootDir>/libs/shared/icons',
    '<rootDir>/libs/picking/features/supply',
    '<rootDir>/libs/picking/features/trip-collectible',
    '<rootDir>/libs/picking/features/trip-sample',
    '<rootDir>/libs/picking/features/trip-picking-end-summary',
    '<rootDir>/libs/picking/features/trip-packing-summary',
    '<rootDir>/libs/picking/features/trip-print-labels',
    '<rootDir>/libs/picking/features/print-selection',
    '<rootDir>/libs/picking/features/dispatch-order',
    '<rootDir>/libs/picking/features/zero-totes-to-pick',
  ],
};
